SELECT [id]
      ,[created_at]
      ,[updated_at]
      ,[short_name]
      ,[name]
      ,[language]
      ,[invoice_relevant]
      ,[supplier]
      ,[client]
      ,[valid_from]
      ,[address_id]
      ,[company_id]
  FROM [dbo].[departments]