SELECT oip.[id]
      ,oip.[created_at]
      ,oip.[updated_at]
      ,oip.[outgoing_invoice_id]
      ,oip.[sequence]
      ,oip.[position_text]
      ,oip.[date_service_from]
      ,oip.[date_service_until]
      ,oip.[type_of_settlement]
      ,oip.[hours]
      ,oip.[hourly_rate]
      ,oip.[netto]
      ,oip.[tax]
      ,oip.[tax_percent]
      ,oip.[gross]
      ,oip.[remark]
      ,oip.[hourly_rate_external]
      ,oip.[netto_external]
      ,oip.[tax_external]
      ,oip.[tax_percent_external]
      ,oip.[gross_external]
      ,oip.[invoice_id_external]
      ,oip.[cost_type_id]
      ,oip.[project_id]
      ,oip.[cost_center_id]
      ,CASE WHEN (LEN(oi.[currency]) = 3) THEN oi.[currency] ELSE 'EUR' END AS [currency]
  FROM [dbo].[outgoing_invoice_positions] oip
  JOIN [dbo].[outgoing_invoices] oi
    ON oi.[id] = oip.[outgoing_invoice_id]
 WHERE [outgoing_invoice_id] = @AUSGANGSRECHNUNGID