SELECT [id]
      ,[created_at]
      ,[updated_at]
      ,[short_name]
      ,[first_name]
      ,[last_name]
      ,[personal_no]
      ,[role_id]
      ,[cost_center_id]
      ,[address_id]
      ,[entry_date]
      ,[leaving_date]
      ,[birthday]
  FROM [DoePaAppDB].[dbo].[staffs]