//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoePaAdminApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoePaAdminApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strAddItem.
        /// </summary>
        public static string strAddItem {
            get {
                return ResourceManager.GetString("strAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strCopy.
        /// </summary>
        public static string strCopy {
            get {
                return ResourceManager.GetString("strCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strEditCostCenter.
        /// </summary>
        public static string strEditCostCenter {
            get {
                return ResourceManager.GetString("strEditCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strEditOrder.
        /// </summary>
        public static string strEditOrder {
            get {
                return ResourceManager.GetString("strEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strEditProject.
        /// </summary>
        public static string strEditProject {
            get {
                return ResourceManager.GetString("strEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strEditWorkforce.
        /// </summary>
        public static string strEditWorkforce {
            get {
                return ResourceManager.GetString("strEditWorkforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strExportChartData.
        /// </summary>
        public static string strExportChartData {
            get {
                return ResourceManager.GetString("strExportChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strImportOutgoingInvoices.
        /// </summary>
        public static string strImportOutgoingInvoices {
            get {
                return ResourceManager.GetString("strImportOutgoingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageAbrechnungseinheiten.
        /// </summary>
        public static string strManageAbrechnungseinheiten {
            get {
                return ResourceManager.GetString("strManageAbrechnungseinheiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageDebitors.
        /// </summary>
        public static string strManageDebitors {
            get {
                return ResourceManager.GetString("strManageDebitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageFeiertage.
        /// </summary>
        public static string strManageFeiertage {
            get {
                return ResourceManager.GetString("strManageFeiertage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageGeschaeftsjahre.
        /// </summary>
        public static string strManageGeschaeftsjahre {
            get {
                return ResourceManager.GetString("strManageGeschaeftsjahre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageKostenstellenarten.
        /// </summary>
        public static string strManageKostenstellenarten {
            get {
                return ResourceManager.GetString("strManageKostenstellenarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageKreditors.
        /// </summary>
        public static string strManageKreditors {
            get {
                return ResourceManager.GetString("strManageKreditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageKunden.
        /// </summary>
        public static string strManageKunden {
            get {
                return ResourceManager.GetString("strManageKunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageOutgoingInvoices.
        /// </summary>
        public static string strManageOutgoingInvoices {
            get {
                return ResourceManager.GetString("strManageOutgoingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManagePostleitzahlen.
        /// </summary>
        public static string strManagePostleitzahlen {
            get {
                return ResourceManager.GetString("strManagePostleitzahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageSkillMenue.
        /// </summary>
        public static string strManageSkillMenue {
            get {
                return ResourceManager.GetString("strManageSkillMenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageTaetigkeiten.
        /// </summary>
        public static string strManageTaetigkeiten {
            get {
                return ResourceManager.GetString("strManageTaetigkeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strManageWaehrungen.
        /// </summary>
        public static string strManageWaehrungen {
            get {
                return ResourceManager.GetString("strManageWaehrungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strPaste.
        /// </summary>
        public static string strPaste {
            get {
                return ResourceManager.GetString("strPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strRefreshView.
        /// </summary>
        public static string strRefreshView {
            get {
                return ResourceManager.GetString("strRefreshView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strRemoveItem.
        /// </summary>
        public static string strRemoveItem {
            get {
                return ResourceManager.GetString("strRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strSaveData.
        /// </summary>
        public static string strSaveData {
            get {
                return ResourceManager.GetString("strSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to strStartMigrationOfInvoices.
        /// </summary>
        public static string strStartMigrationOfInvoices {
            get {
                return ResourceManager.GetString("strStartMigrationOfInvoices", resourceCulture);
            }
        }
    }
}
