//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACCApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACCApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strAddItem ähnelt.
        /// </summary>
        public static string strAddItem {
            get {
                return ResourceManager.GetString("strAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strCopy ähnelt.
        /// </summary>
        public static string strCopy {
            get {
                return ResourceManager.GetString("strCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strEditCostCenter ähnelt.
        /// </summary>
        public static string strEditCostCenter {
            get {
                return ResourceManager.GetString("strEditCostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strEditOrder ähnelt.
        /// </summary>
        public static string strEditOrder {
            get {
                return ResourceManager.GetString("strEditOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strEditProject ähnelt.
        /// </summary>
        public static string strEditProject {
            get {
                return ResourceManager.GetString("strEditProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strEditWorkforce ähnelt.
        /// </summary>
        public static string strEditWorkforce {
            get {
                return ResourceManager.GetString("strEditWorkforce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strExportChartData ähnelt.
        /// </summary>
        public static string strExportChartData {
            get {
                return ResourceManager.GetString("strExportChartData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strImportOutgoingInvoices ähnelt.
        /// </summary>
        public static string strImportOutgoingInvoices {
            get {
                return ResourceManager.GetString("strImportOutgoingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageAbrechnungseinheiten ähnelt.
        /// </summary>
        public static string strManageAbrechnungseinheiten {
            get {
                return ResourceManager.GetString("strManageAbrechnungseinheiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageDebitors ähnelt.
        /// </summary>
        public static string strManageDebitors {
            get {
                return ResourceManager.GetString("strManageDebitors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageFeiertage ähnelt.
        /// </summary>
        public static string strManageFeiertage {
            get {
                return ResourceManager.GetString("strManageFeiertage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageGeschaeftsjahre ähnelt.
        /// </summary>
        public static string strManageGeschaeftsjahre {
            get {
                return ResourceManager.GetString("strManageGeschaeftsjahre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageKostenstellenarten ähnelt.
        /// </summary>
        public static string strManageKostenstellenarten {
            get {
                return ResourceManager.GetString("strManageKostenstellenarten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageKreditors ähnelt.
        /// </summary>
        public static string strManageKreditors {
            get {
                return ResourceManager.GetString("strManageKreditors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageKunden ähnelt.
        /// </summary>
        public static string strManageKunden {
            get {
                return ResourceManager.GetString("strManageKunden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageOutgoingInvoices ähnelt.
        /// </summary>
        public static string strManageOutgoingInvoices {
            get {
                return ResourceManager.GetString("strManageOutgoingInvoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManagePostleitzahlen ähnelt.
        /// </summary>
        public static string strManagePostleitzahlen {
            get {
                return ResourceManager.GetString("strManagePostleitzahlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageSkillMenue ähnelt.
        /// </summary>
        public static string strManageSkillMenue {
            get {
                return ResourceManager.GetString("strManageSkillMenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageTaetigkeiten ähnelt.
        /// </summary>
        public static string strManageTaetigkeiten {
            get {
                return ResourceManager.GetString("strManageTaetigkeiten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strManageWaehrungen ähnelt.
        /// </summary>
        public static string strManageWaehrungen {
            get {
                return ResourceManager.GetString("strManageWaehrungen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strPaste ähnelt.
        /// </summary>
        public static string strPaste {
            get {
                return ResourceManager.GetString("strPaste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strRefreshView ähnelt.
        /// </summary>
        public static string strRefreshView {
            get {
                return ResourceManager.GetString("strRefreshView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strRemoveItem ähnelt.
        /// </summary>
        public static string strRemoveItem {
            get {
                return ResourceManager.GetString("strRemoveItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strSaveData ähnelt.
        /// </summary>
        public static string strSaveData {
            get {
                return ResourceManager.GetString("strSaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strSelectSkillMenue ähnelt.
        /// </summary>
        public static string strSelectSkillMenue {
            get {
                return ResourceManager.GetString("strSelectSkillMenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die strStartMigrationOfInvoices ähnelt.
        /// </summary>
        public static string strStartMigrationOfInvoices {
            get {
                return ResourceManager.GetString("strStartMigrationOfInvoices", resourceCulture);
            }
        }
    }
}
