SELECT [id]
      ,[created_at]
      ,[updated_at]
      ,[title]
      ,[first_name]
      ,[last_name]
      ,[language]
      ,[sex]
      ,[position]
      ,[formal]
      ,[staff_id_main_contact]
      ,[staff_contacts]
      ,[email_private]
      ,[address_id_private]
      ,[department_id]
      ,[email]
      ,[telephon]
      ,[mobil]
      ,[remark]
      ,[valid_from]
  FROM [dbo].[contacts]