SELECT [id]
      ,[created_at]
      ,[updated_at]
      ,[addition1]
      ,[addition2]
      ,[street]
      ,[street_number]
      ,[postcode]
      ,[city]
      ,[district]
      ,[state]
      ,[country]
  FROM [dbo].[addresses]