SELECT [id]
      ,[created_at]
      ,[updated_at]
      ,[short_name]
      ,[name1]
      ,[name2]
      ,[valid_from]
      ,[address_id]
      ,[reverse_charge]
      ,[vat_no]
  FROM [dbo].[companies]